# Generated by Django 5.2.16 on 2026-07-13 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otpverification',
            name='email',
            field=models.EmailField(db_index=True, max_length=254),
        ),
    ]
