# Generated by Django 5.2.16 on 2026-07-12 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FraudLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entity_name', models.CharField(max_length=255)),
                ('trigger', models.CharField(max_length=255)),
                ('risk_score', models.CharField(max_length=50)),
                ('date', models.DateField(auto_now_add=True)),
                ('is_dismissed', models.BooleanField(default=False)),
            ],
        ),
    ]
