# Generated by Django 5.2.16 on 2026-07-12 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='logisticsjob',
            name='qr_code_content',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='logisticsjob',
            name='verification_token',
            field=models.CharField(blank=True, max_length=64, null=True, unique=True),
        ),
    ]
