# Generated by Django 5.2.16 on 2026-07-12 07:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NGO',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('lat', models.FloatField()),
                ('lng', models.FloatField()),
                ('address', models.TextField()),
                ('registration_number', models.CharField(max_length=100)),
                ('gov_registration_number', models.CharField(max_length=100)),
                ('ngo_type', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=20)),
                ('website', models.URLField(blank=True, null=True)),
                ('state', models.CharField(max_length=100)),
                ('district', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('pin_code', models.CharField(max_length=20)),
                ('description', models.TextField()),
                ('mission', models.TextField()),
                ('working_areas', models.CharField(max_length=500)),
                ('operating_since', models.CharField(max_length=4)),
                ('volunteers_count', models.PositiveIntegerField(default=0)),
                ('verification_status', models.CharField(choices=[('pending', 'Pending Audit'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('changes_requested', 'Changes Requested')], default='pending', max_length=20)),
                ('rejection_reason', models.TextField(blank=True, null=True)),
                ('trust_score', models.IntegerField(default=70)),
                ('response_time', models.CharField(default='--', max_length=20)),
                ('success_rate', models.CharField(default='--', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ngo_details', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Need',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=100)),
                ('item', models.CharField(max_length=255)),
                ('quantity', models.PositiveIntegerField()),
                ('urgency', models.CharField(choices=[('High', 'High'), ('Medium', 'Medium'), ('Low', 'Low')], max_length=20)),
                ('description', models.TextField(blank=True, null=True)),
                ('lat', models.FloatField()),
                ('lng', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ngo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='needs', to='ngo.ngo')),
            ],
        ),
        migrations.CreateModel(
            name='NGOReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author_name', models.CharField(max_length=255)),
                ('rating', models.PositiveIntegerField(default=5)),
                ('comment', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ngo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='ngo.ngo')),
            ],
        ),
        migrations.CreateModel(
            name='NGODocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc_type', models.CharField(choices=[('govRegCert', 'Gov Registration Certificate'), ('panCard', 'PAN Card Copy'), ('trustRegCert', 'Trust Registration Certificate'), ('doc80G', '80G Exemption Certificate'), ('doc12A', '12A Registration Certificate'), ('logo', 'NGO Logo Brand'), ('officePhoto', 'Registered Office Photo'), ('authPersonPhoto', 'Authorized Person Photo'), ('addressProof', 'Office Address Proof'), ('idProof', 'Authorized Person ID Proof'), ('verificationLetter', 'Verification Request Letter')], max_length=30)),
                ('file_url', models.URLField(max_length=500)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('ngo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='ngo.ngo')),
            ],
            options={
                'unique_together': {('ngo', 'doc_type')},
            },
        ),
    ]
