# Generated by Django 5.2.16 on 2026-07-12 08:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ngo', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EmergencyCampaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('location', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='need',
            name='fulfilled_quantity',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ngodocument',
            name='doc_type',
            field=models.CharField(choices=[('govRegCert', 'Gov Registration Certificate'), ('panCard', 'PAN Card Copy'), ('trustRegCert', 'Trust Registration Certificate'), ('doc80G', '80G Exemption Certificate'), ('doc12A', '12A Registration Certificate'), ('logo', 'NGO Logo Brand'), ('officePhoto', 'Registered Office Photo'), ('authPersonPhoto', 'Authorized Person Photo'), ('addressProof', 'Office Address Proof'), ('idProof', 'Authorized Person ID Proof'), ('verificationLetter', 'Verification Request Letter'), ('logoImg', 'NGO Brand Logo')], max_length=30),
        ),
        migrations.AddField(
            model_name='need',
            name='campaign',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='needs', to='ngo.emergencycampaign'),
        ),
        migrations.CreateModel(
            name='VolunteerEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('date', models.DateTimeField()),
                ('location', models.CharField(max_length=255)),
                ('max_volunteers', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ngo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='ngo.ngo')),
            ],
        ),
        migrations.CreateModel(
            name='VolunteerRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registered_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(default='approved', max_length=20)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registrations', to='ngo.volunteerevent')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('event', 'user')},
            },
        ),
    ]
