# Generated by Django 5.2.16 on 2026-07-26 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ngo', '0004_alter_need_category_alter_ngo_verification_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='need',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('ACTIVE', 'Active'), ('ACCEPTED', 'Accepted'), ('FULFILLED', 'Fulfilled'), ('REJECTED', 'Rejected'), ('CANCELLED', 'Cancelled'), ('EXPIRED', 'Expired')], db_index=True, default='ACTIVE', max_length=20),
        ),
    ]
