# Generated by Django 5.2.16 on 2026-07-12 08:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ngo', '0002_emergencycampaign_need_fulfilled_quantity_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='ngodocument',
            unique_together=set(),
        ),
    ]
