# Generated by Django 5.2.16 on 2026-07-13 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ngo', '0003_alter_ngodocument_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='need',
            name='category',
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='ngo',
            name='verification_status',
            field=models.CharField(choices=[('pending', 'Pending Audit'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('changes_requested', 'Changes Requested')], db_index=True, default='pending', max_length=20),
        ),
    ]
