# Generated by Django 5.2.16 on 2026-07-25 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_delete_otpverification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='avatar',
            field=models.CharField(default='👩\u200d💼', max_length=500),
        ),
    ]
