# Generated by Django 5.2.16 on 2026-07-12 07:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('donation', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LogisticsJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('carrier_name', models.CharField(default='Express Cargo #DB-990', max_length=100)),
                ('current_step', models.PositiveIntegerField(default=1)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('donation', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='logistics_job', to='donation.donation')),
            ],
        ),
        migrations.CreateModel(
            name='TrackingMilestone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step_num', models.PositiveIntegerField()),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('lat', models.FloatField()),
                ('lng', models.FloatField()),
                ('time_stamp', models.DateTimeField(auto_now_add=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='milestones', to='logistics.logisticsjob')),
            ],
            options={
                'ordering': ['step_num'],
                'unique_together': {('job', 'step_num')},
            },
        ),
    ]
