# Generated by Django 5.2.16 on 2026-07-13 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donation', '0002_communitychallenge'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donation',
            name='category',
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='donation',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending Moderation'), ('VERIFIED', 'Verified/Approved'), ('REJECTED', 'Rejected'), ('MATCHED', 'Matched/Claimed'), ('DELIVERED', 'Delivered')], db_index=True, default='PENDING', max_length=20),
        ),
    ]
