# Generated by Django 5.2.16 on 2026-07-25 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('all', 'All'), ('delivery', 'Delivery Status'), ('security', 'Security Alert'), ('match', 'Donation Match')], default='all', max_length=20),
        ),
    ]
